services:
  backend:
    build:
      context: ./Backend
    container_name: backend-container
    ports:
      - "8010:8010"
    volumes:
      - ./Backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./Frontend
    container_name: frontend-container
    ports:
      - "80:80"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
