version: '3.9'

services:
  fastapi-app:
    build:
      context: ./Backend   # Look inside Backend for Dockerfile
    container_name: fastapi-container
    ports:
      - "8010:8010"
    volumes:
      - ./Backend:/app
    environment:
      - PYTHONUNBUFFERED=1

